"""
[LintCode 2216] String summing, repeated output, slicing
Link: https://www.lintcode.com/problem/2216/

This question has two strings str_1 and str_2. We need you to complete the code in solution.py to achieve:

Add the strings str_1 and str_2 to get a new string;
Multiply str_1 by 2 to get a new string;
Slice str_1 to get the data of the string index 1 to 4, that is, the part of index 1, 2, 3, to get a new string.
Finally, return the three new strings generated by the above three operations.

We will import the code you perfected in solution.py into main.py and run it. If your code logic runs correctly, the program will output the result of the two string operations.
"""


def add_repeat_slicing(str_1: str, str_2: str) -> tuple:
    """
    :param str_1: The first source string
    :param str_2: The Second source string
    :return: tuple: A tuple containing three new strings
    """
    # -- write your code here --
    return str_1 + str_2, str_1 * 2, str_1[1:4]
